name: Build
on:
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: henkelmax.public
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Unit tests
        run: mvn -B test
      - name: Publish to maxhenkel.de
        run: mvn -Dmaven.test.skip=true -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}